GET "http://localhost:3002/api/v1/user/get-user" HTTP/1.1


### POST request to login-user
POST https://redux-mart-server.onrender.com/api/v1/user/login-user
Content-Type: application/json

{

   "username" :"redux_mart",
   "password": "123"
 
}